version: '3.7'
services:

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017

  shortener:
    container_name: shortener
    build: ./
    expose:
      - 8080
    ports:
      - 8080:8080